# Generated by Django 4.1.6 on 2023-02-05 02:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("checksum", models.CharField(max_length=32, null=True)),
                ("file_path", models.CharField(max_length=255, unique=True)),
                ("header_tag", models.CharField(max_length=255)),
                ("mime", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Volume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("volume_path", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
